### PR TITLE
Pull Request

### PR DESCRIPTION
**Pull request by Mattymerr**
This contains a fix to make the plugin only initialize itself once and also a little bit of code
to make it show a screen when there is no active vessel. there is also code to hopefully
fix the LCD applet from being onscreen indefinitely when KSP crashes, reason why it isn't merged is talked about bellow.

Not sure how much of this you want.

the assembly/file version has also been changed to 1.2.1/1.2.1.1 (1.2.1.1 for the crash fix, though it should be 1.2.1 or 1.2.2) not that it makes much of a difference

You might want to check through it and make sure it is all good.
Also might want to definitely look through the readme and most likely edit it.

One other thing, there are 2 other branches that you might want to check.
They are autobuilder and crashfix
Autobuilder is almost all just build events to make testing and packaging releases faster (for me anyway, you might like to do it differently). I made it mainly for myself.
A bit more (verbose) info is in the autobuilder.md file.

crashfix contains code to hopefully fix the LCD applet being left onscreen after a crash, the plugin just needs to be run again and it should automatically clean it up hopefully. it isn't in the master branch as i'm not sure whether you want untested code in the plugin.

### CODE REVIEW

**Comment by Mattymerr** [comment]
might not want to read all of the text I wrote, just an outline of what I have uploaded.
sorry if it is hard to understand all of it, didn't mean for it to get so long.

**Comment by BGog** [comment]
Thank you Mattymerr!

I'll try it out tomorrow when I get home.   Could you send a pull request for the crash fix as well.

**Comment by Mattymerr** [comment]
Most of the commits there are trivial things that got into the master branch but were meant to go into a seperate branch so they didn't spam it (which they did). I will send a pull request for the theoretical crash fix now.

**Comment by BGog** [comment]
Hello.   Sorry for the delay.  I was called out of town on a business trip.  I'm hoping to get a version out sometime this weekend.

**Pull request merged**
